import {
  Backpack,
  FileText,
  Headphones,
  KeyRound,
  Smartphone,
  WalletCards,
} from '@lucide/vue'

export const categories = ['全部', '证件卡片', '数码设备', '随身物品', '书本文具']
export const places = ['全部地点', '图书馆', '教学楼', '食堂', '操场', '宿舍区']

export const items = [
  {
    id: 1,
    type: 'found',
    category: '数码设备',
    title: '银灰色无线耳机盒',
    description: '在二教 A 区靠窗座位发现，盒盖有一道很浅的划痕。为避免冒领，耳机盒内部的具体标记将在认领时核对。',
    location: '第二教学楼 A 区',
    placeGroup: '教学楼',
    time: '今天 14:20',
    eventTime: '2026-07-17 13:50 左右',
    dateOrder: 8,
    icon: Headphones,
    tone: 'sage',
    clues: 3,
    views: 126,
    verified: true,
    hot: true,
    publisher: '林同学',
    publisherMeta: '计算机学院 · 校园身份已核验',
  },
  {
    id: 2,
    type: 'lost',
    category: '证件卡片',
    title: '蓝色校园卡套',
    description: '卡套背面贴了一枚小企鹅贴纸，可能掉在图书馆三层到东门之间。卡内证件姓名首字母为 L。',
    location: '图书馆三层',
    placeGroup: '图书馆',
    time: '今天 12:05',
    eventTime: '2026-07-17 10:30—11:40',
    dateOrder: 7,
    icon: WalletCards,
    tone: 'blue',
    clues: 6,
    views: 208,
    verified: true,
    hot: false,
    publisher: 'L 同学',
    publisherMeta: '外国语学院 · 校园身份已核验',
  },
  {
    id: 3,
    type: 'found',
    category: '随身物品',
    title: '一串宿舍钥匙',
    description: '红色挂绳，钥匙圈上有一个透明数字牌。具体数字未公开，认领时需要准确说明。',
    location: '南区食堂门口',
    placeGroup: '食堂',
    time: '昨天 19:40',
    eventTime: '2026-07-16 19:30 左右',
    dateOrder: 6,
    icon: KeyRound,
    tone: 'amber',
    clues: 2,
    views: 89,
    verified: false,
    hot: false,
    publisher: '热心同学',
    publisherMeta: '账号注册 186 天',
  },
  {
    id: 4,
    type: 'lost',
    category: '随身物品',
    title: '黑色双肩包',
    description: '包侧面放着一把透明雨伞，内有专业课笔记和水杯。最后一次确认是在西操场看台。',
    location: '西操场看台',
    placeGroup: '操场',
    time: '昨天 17:10',
    eventTime: '2026-07-16 16:20—17:10',
    dateOrder: 5,
    icon: Backpack,
    tone: 'ink',
    clues: 8,
    views: 311,
    verified: true,
    hot: true,
    publisher: '周同学',
    publisherMeta: '管理学院 · 校园身份已核验',
  },
  {
    id: 5,
    type: 'found',
    category: '数码设备',
    title: '白色充电宝',
    description: '在一食堂二楼靠近饮水机的位置捡到，已交服务台保管。外壳侧面有一处小贴纸。',
    location: '第一食堂二楼',
    placeGroup: '食堂',
    time: '7 月 15 日',
    eventTime: '2026-07-15 12:00 左右',
    dateOrder: 4,
    icon: Smartphone,
    tone: 'coral',
    clues: 1,
    views: 74,
    verified: true,
    hot: false,
    publisher: '食堂服务台',
    publisherMeta: '校园服务点 · 官方账号',
  },
  {
    id: 6,
    type: 'lost',
    category: '书本文具',
    title: '《数据结构》笔记本',
    description: '牛皮纸封面，扉页写有班级缩写，最后一页夹着课程表。笔记对考试很重要。',
    location: '综合楼 407',
    placeGroup: '教学楼',
    time: '7 月 14 日',
    eventTime: '2026-07-14 15:00—17:30',
    dateOrder: 3,
    icon: FileText,
    tone: 'paper',
    clues: 4,
    views: 132,
    verified: false,
    hot: false,
    publisher: '匿名同学',
    publisherMeta: '账号注册 92 天',
  },
]
